/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import audio.AePlayWave;
import audio.PlayAudio;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Neft
 */
public class Juego extends javax.swing.JFrame {

    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        textoJugador1 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        textoJugador2 = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        btnComenzar = new javax.swing.JButton();
        textoComenzar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 70));
        jLabel1.setFont(new java.awt.Font("MathJax_Math", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/superior.png"))); // NOI18N
        jLabel1.setText("El juego del gato");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadros.jpg"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoJugador1.setText("Jugador 1:");
        textoJugador1.setOpaque(true);
        jPanel3.add(textoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 244, 30));
        jPanel3.add(txtJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 244, 30));

        textoJugador2.setText("Jugador 2:");
        textoJugador2.setOpaque(true);
        jPanel3.add(textoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 244, 30));
        jPanel3.add(txtJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 244, 30));

        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanca.jpg"))); // NOI18N
        btnComenzar.setDisabledIcon(null);
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        jPanel3.add(btnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        textoComenzar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        textoComenzar.setText("Comenzar");
        jPanel3.add(textoComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn3.isEnabled()){//Si no es turno de nadie y el boton esta activado
            btn3.setEnabled(false);//desactivamos el boton
            btn3.setActionCommand(turno);//le asignamos el action command igual al turno actual
            if(turno=="X"){//si el turno es de las x
                btn3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{//sino es de las O
               btn3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try { //Reproduce el sonido
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();//comprueba si alguien gano
        }else{
            try {//reproduce el audio alternativo en caso de que ese boton no sea una opción válida
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        // TODO add your handling code here:
        if(!(txtJugador1.getText().isEmpty() || txtJugador2.getText().isEmpty())){ //Si los nombres ya fueron escritos
            if(turno.isEmpty()&&nTurno==0){//Si no hay turno y no hay numero de turno, es decir, la partida aun no inicia
                Random random = new Random();//Se crea un objeto de la clase random
                if(random.nextBoolean()){//Se llama a un booleano random, es decir, elige aleatoriamente true o false
                    turno = "X"; //Si el random es true, le toca primero a las X
                    textoJugador1.setBackground(Color.green);
                }else{
                    turno = "O";//Si es falso le toca primero a las O
                    textoJugador2.setBackground(Color.green);
                }
                txtJugador1.setEnabled(false);//Se desactivan los cuadros de texto para evitar cambios mientras se juega
                txtJugador2.setEnabled(false);
                //Se reinicia todo el tablero
                btn1.setActionCommand("");btn1.setEnabled(true);
                btn2.setActionCommand("");btn2.setEnabled(true);
                btn3.setActionCommand("");btn3.setEnabled(true);
                btn4.setActionCommand("");btn4.setEnabled(true);
                btn5.setActionCommand("");btn5.setEnabled(true);
                btn6.setActionCommand("");btn6.setEnabled(true);
                btn7.setActionCommand("");btn7.setEnabled(true);
                btn8.setActionCommand("");btn8.setEnabled(true);
                btn9.setActionCommand("");btn9.setEnabled(true);
                //Se cambia la imagen y el texto por el de reiniciar
                btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roja.jpeg")));
                textoComenzar.setText("Reiniciar");
                
            }else{//Si ya se esta dentro de una partida
                if(JOptionPane.showConfirmDialog(null, "¿estás seguro?")==0){//Muestra un cuadro de confirmacion de que se quiere reiniciar la partida
                    txtJugador1.setEnabled(true);//Se activan los cuadros de texto para modificarlos
                    txtJugador2.setEnabled(true);
                    //Se quita el color de los jugadores
                    textoJugador1.setBackground(null);
                    textoJugador2.setBackground(null);
                    //Se reinicia todo el tablero
                    btn1.setActionCommand("");btn1.setEnabled(true);
                    btn2.setActionCommand("");btn2.setEnabled(true);
                    btn3.setActionCommand("");btn3.setEnabled(true);
                    btn4.setActionCommand("");btn4.setEnabled(true);
                    btn5.setActionCommand("");btn5.setEnabled(true);
                    btn6.setActionCommand("");btn6.setEnabled(true);
                    btn7.setActionCommand("");btn7.setEnabled(true);
                    btn8.setActionCommand("");btn8.setEnabled(true);
                    btn9.setActionCommand("");btn9.setEnabled(true);
                    //Se cambia la imagen y el texto por el de comenzar
                    btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanca.jpg")));
                    textoComenzar.setText("Comenzar");
                    //Se reinicia la variable del turno
                    turno = "";
                    nTurno = 0;
                }//Si no se quiere reiniciar no se hace nada
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nombres no definidos");
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // Lo que sucede en los botones es similar a lo que ocurre en el boton 3 (antes visto)
        //Lo unico que cambia es el boton
        if(!turno.isEmpty() && btn1.isEnabled()){
            btn1.setEnabled(false);
            btn1.setActionCommand(turno);
            if(turno=="X"){
                btn1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn2.isEnabled()){
            btn2.setEnabled(false);
            btn2.setActionCommand(turno);
            if(turno=="X"){
                btn2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn4.isEnabled()){
            btn4.setEnabled(false);
            btn4.setActionCommand(turno);
            if(turno=="X"){
                btn4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn5.isEnabled()){
            btn5.setEnabled(false);
            btn5.setActionCommand(turno);
            if(turno=="X"){
                btn5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn6.isEnabled()){
            btn6.setEnabled(false);
            btn6.setActionCommand(turno);
            if(turno=="X"){
                btn6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn7.isEnabled()){
            btn7.setEnabled(false);
            btn7.setActionCommand(turno);
            if(turno=="X"){
                btn7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn8.isEnabled()){
            btn8.setEnabled(false);
            btn8.setActionCommand(turno);
            if(turno=="X"){
                btn8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(!turno.isEmpty() && btn9.isEnabled()){
            btn9.setEnabled(false);
            btn9.setActionCommand(turno);
            if(turno=="X"){
                btn9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.jpeg")));
            }else{
               btn9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.jpeg")));
            }
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            victoria();
        }else{
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/no.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_btn9ActionPerformed

    public void victoria(){//Metodo que verifica si alguien ha ganado o si ya se ha empatado
        nTurno++;
        if(btn1.getActionCommand().equals(btn2.getActionCommand()) &&
                btn2.getActionCommand().equals(btn3.getActionCommand()) && 
                !btn3.getActionCommand().isEmpty()){//Comprueba cada una de las distintas combinacion para ganar
            try {//En caso de ganar reproduce el sonido
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            //Muestra el mensaje de quien gano y modifica el turno para que ya no sea de nadie
            //Se pone un if dentro del show message dialog de la forma:
            // condicion ? true : false
            //Si ganaron las X toma el texto del primer cuadro de texto, si no del segundo
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
            
        }
        else if(btn4.getActionCommand().equals(btn5.getActionCommand()) &&
                btn5.getActionCommand().equals(btn6.getActionCommand()) && 
                !btn6.getActionCommand().isEmpty()){
//Se utilizan else if ya que si no es una es la otra y si es alguna las demas ya no aplican
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
        }
        else if(btn7.getActionCommand().equals(btn8.getActionCommand()) &&
                btn8.getActionCommand().equals(btn9.getActionCommand()) && 
                !btn9.getActionCommand().isEmpty()){
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
        }
        else if(btn1.getActionCommand().equals(btn4.getActionCommand()) &&
                btn4.getActionCommand().equals(btn7.getActionCommand()) && 
                !btn7.getActionCommand().isEmpty()){
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
        }
        else if(btn2.getActionCommand().equals(btn5.getActionCommand()) &&
                btn5.getActionCommand().equals(btn8.getActionCommand()) && 
                !btn8.getActionCommand().isEmpty()){
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
        }
        else if(btn3.getActionCommand().equals(btn6.getActionCommand()) &&
                btn6.getActionCommand().equals(btn9.getActionCommand()) && 
                !btn9.getActionCommand().isEmpty()){
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
        }
        else if(btn1.getActionCommand().equals(btn5.getActionCommand()) &&
                btn5.getActionCommand().equals(btn9.getActionCommand()) && 
                !btn9.getActionCommand().isEmpty()){
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
        }
        else if(btn3.getActionCommand().equals(btn5.getActionCommand()) &&
                btn5.getActionCommand().equals(btn7.getActionCommand()) && 
                !btn7.getActionCommand().isEmpty()){
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/gano.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null,"Gano " + (turno.equals("X") ? txtJugador1.getText():txtJugador2.getText()));
            turno="";
            
        }
        else if(nTurno==9){//Si nadie gano y el turno es el 9 (Se lleno el tablero)
            try {//Reproduce el sonido de empate
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/empate.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null, "Empate :(");//Se muestra el mensaje de empate
        }else{
            //Se cambia el resaltado de los botones
            //Se vuelve a utilizar el if dentro de la asignacion
            turno = (turno.equals("X") ? "O" : "X");  
            if(turno.equals("X")){//Si es turno de las x se resalta al jugador de las x
                textoJugador1.setBackground(Color.green);  
                textoJugador2.setBackground(null);
            }
            else{//sino se resalta al jugador de las O
                textoJugador1.setBackground(null);  
                textoJugador2.setBackground(Color.green);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel textoComenzar;
    private javax.swing.JLabel textoJugador1;
    private javax.swing.JLabel textoJugador2;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
    String turno = ""; //Verifica de quien es el turno, si no tiene nada es porque la partida no ha comenzado
    int nTurno = 0; //Verifica si no se ha llegado al ultimo turno (9) empate
}
